
// Generated by Cadence Encounter(R) RTL Compiler RC14.27 - v14.20-s064_1

// Verification Directory fv/PWM 

module increment_unsigned(A, CI, Z);
  input [26:0] A;
  input CI;
  output [26:0] Z;
  wire [26:0] A;
  wire CI;
  wire [26:0] Z;
  wire n_1, n_3, n_4, n_6, n_7, n_9, n_10, n_12;
  wire n_13, n_15, n_16, n_18, n_19, n_21, n_22, n_24;
  wire n_25, n_27, n_28, n_30, n_31, n_33, n_34, n_36;
  wire n_37, n_39, n_40, n_42, n_43, n_45, n_46, n_48;
  wire n_49, n_51, n_52, n_54, n_55, n_57, n_58, n_60;
  wire n_61, n_63, n_64, n_66, n_67, n_69, n_70, n_72;
  wire n_73;
  XNOR2_X1 g182(.A (n_73), .B (A[26]), .ZN (Z[26]));
  XNOR2_X1 g183(.A (n_70), .B (A[25]), .ZN (Z[25]));
  NAND2_X1 g184(.A1 (n_72), .A2 (A[25]), .ZN (n_73));
  INV_X1 g185(.A (n_70), .ZN (n_72));
  XNOR2_X1 g186(.A (n_67), .B (A[24]), .ZN (Z[24]));
  NAND2_X1 g187(.A1 (n_69), .A2 (A[24]), .ZN (n_70));
  INV_X1 g188(.A (n_67), .ZN (n_69));
  XNOR2_X1 g189(.A (n_64), .B (A[23]), .ZN (Z[23]));
  NAND2_X1 g190(.A1 (n_66), .A2 (A[23]), .ZN (n_67));
  INV_X1 g191(.A (n_64), .ZN (n_66));
  XNOR2_X1 g192(.A (n_61), .B (A[22]), .ZN (Z[22]));
  NAND2_X1 g193(.A1 (n_63), .A2 (A[22]), .ZN (n_64));
  INV_X1 g194(.A (n_61), .ZN (n_63));
  XNOR2_X1 g195(.A (n_58), .B (A[21]), .ZN (Z[21]));
  NAND2_X1 g196(.A1 (n_60), .A2 (A[21]), .ZN (n_61));
  INV_X1 g197(.A (n_58), .ZN (n_60));
  XNOR2_X1 g198(.A (n_55), .B (A[20]), .ZN (Z[20]));
  NAND2_X1 g199(.A1 (n_57), .A2 (A[20]), .ZN (n_58));
  INV_X1 g200(.A (n_55), .ZN (n_57));
  XNOR2_X1 g201(.A (n_52), .B (A[19]), .ZN (Z[19]));
  NAND2_X1 g202(.A1 (n_54), .A2 (A[19]), .ZN (n_55));
  INV_X1 g203(.A (n_52), .ZN (n_54));
  XNOR2_X1 g204(.A (n_49), .B (A[18]), .ZN (Z[18]));
  NAND2_X1 g205(.A1 (n_51), .A2 (A[18]), .ZN (n_52));
  INV_X1 g206(.A (n_49), .ZN (n_51));
  XNOR2_X1 g207(.A (n_46), .B (A[17]), .ZN (Z[17]));
  NAND2_X1 g208(.A1 (n_48), .A2 (A[17]), .ZN (n_49));
  INV_X1 g209(.A (n_46), .ZN (n_48));
  XNOR2_X1 g210(.A (n_43), .B (A[16]), .ZN (Z[16]));
  NAND2_X1 g211(.A1 (n_45), .A2 (A[16]), .ZN (n_46));
  INV_X1 g212(.A (n_43), .ZN (n_45));
  XNOR2_X1 g213(.A (n_40), .B (A[15]), .ZN (Z[15]));
  NAND2_X1 g214(.A1 (n_42), .A2 (A[15]), .ZN (n_43));
  INV_X1 g215(.A (n_40), .ZN (n_42));
  XNOR2_X1 g216(.A (n_37), .B (A[14]), .ZN (Z[14]));
  NAND2_X1 g217(.A1 (n_39), .A2 (A[14]), .ZN (n_40));
  INV_X1 g218(.A (n_37), .ZN (n_39));
  XNOR2_X1 g219(.A (n_34), .B (A[13]), .ZN (Z[13]));
  NAND2_X1 g220(.A1 (n_36), .A2 (A[13]), .ZN (n_37));
  INV_X1 g221(.A (n_34), .ZN (n_36));
  XNOR2_X1 g222(.A (n_31), .B (A[12]), .ZN (Z[12]));
  NAND2_X1 g223(.A1 (n_33), .A2 (A[12]), .ZN (n_34));
  INV_X1 g224(.A (n_31), .ZN (n_33));
  XNOR2_X1 g225(.A (n_28), .B (A[11]), .ZN (Z[11]));
  NAND2_X1 g226(.A1 (n_30), .A2 (A[11]), .ZN (n_31));
  INV_X1 g227(.A (n_28), .ZN (n_30));
  XNOR2_X1 g228(.A (n_25), .B (A[10]), .ZN (Z[10]));
  NAND2_X1 g229(.A1 (n_27), .A2 (A[10]), .ZN (n_28));
  INV_X1 g230(.A (n_25), .ZN (n_27));
  XNOR2_X1 g231(.A (n_22), .B (A[9]), .ZN (Z[9]));
  NAND2_X1 g232(.A1 (n_24), .A2 (A[9]), .ZN (n_25));
  INV_X1 g233(.A (n_22), .ZN (n_24));
  XNOR2_X1 g234(.A (n_19), .B (A[8]), .ZN (Z[8]));
  NAND2_X1 g235(.A1 (n_21), .A2 (A[8]), .ZN (n_22));
  INV_X1 g236(.A (n_19), .ZN (n_21));
  XNOR2_X1 g237(.A (n_16), .B (A[7]), .ZN (Z[7]));
  NAND2_X1 g238(.A1 (n_18), .A2 (A[7]), .ZN (n_19));
  INV_X1 g239(.A (n_16), .ZN (n_18));
  XNOR2_X1 g240(.A (n_13), .B (A[6]), .ZN (Z[6]));
  NAND2_X1 g241(.A1 (n_15), .A2 (A[6]), .ZN (n_16));
  INV_X1 g242(.A (n_13), .ZN (n_15));
  XNOR2_X1 g243(.A (n_10), .B (A[5]), .ZN (Z[5]));
  NAND2_X1 g244(.A1 (n_12), .A2 (A[5]), .ZN (n_13));
  INV_X1 g245(.A (n_10), .ZN (n_12));
  XNOR2_X1 g246(.A (n_7), .B (A[4]), .ZN (Z[4]));
  NAND2_X1 g247(.A1 (n_9), .A2 (A[4]), .ZN (n_10));
  INV_X1 g248(.A (n_7), .ZN (n_9));
  XNOR2_X1 g249(.A (n_4), .B (A[3]), .ZN (Z[3]));
  NAND2_X1 g250(.A1 (n_6), .A2 (A[3]), .ZN (n_7));
  INV_X1 g251(.A (n_4), .ZN (n_6));
  XNOR2_X1 g252(.A (n_1), .B (A[2]), .ZN (Z[2]));
  NAND2_X1 g253(.A1 (n_3), .A2 (A[2]), .ZN (n_4));
  INV_X1 g254(.A (n_1), .ZN (n_3));
  XOR2_X1 g255(.A (A[1]), .B (A[0]), .Z (Z[1]));
  NAND2_X1 g256(.A1 (A[1]), .A2 (A[0]), .ZN (n_1));
endmodule

module PWM(clk, reset, LED);
  input clk, reset;
  output LED;
  wire clk, reset;
  wire LED;
  wire [26:0] cnt;
  wire [3:0] pwm_cnt;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_79;
  increment_unsigned inc_add_12_12_1(.A (cnt), .CI (1'b1), .Z ({n_51,
       n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61,
       n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71,
       n_72, n_73, n_74, n_75, n_76, UNCONNECTED}));
  OAI22_X1 g248(.A1 (n_48), .A2 (n_40), .B1 (n_49), .B2 (pwm_cnt[3]),
       .ZN (LED));
  NOR2_X1 g249(.A1 (n_47), .A2 (n_45), .ZN (n_49));
  NOR3_X1 g250(.A1 (n_47), .A2 (n_45), .A3 (n_38), .ZN (n_48));
  AOI221_X1 g251(.A (n_46), .B1 (n_44), .B2 (pwm_cnt[1]), .C1 (n_41),
       .C2 (pwm_cnt[2]), .ZN (n_47));
  AOI21_X1 g252(.A (n_42), .B1 (n_43), .B2 (n_0), .ZN (n_46));
  NOR2_X1 g253(.A1 (n_41), .A2 (pwm_cnt[2]), .ZN (n_45));
  INV_X1 g254(.A (n_43), .ZN (n_44));
  AOI211_X1 g255(.A (cnt[0]), .B (n_39), .C1 (cnt[22]), .C2 (cnt[26]),
       .ZN (n_43));
  XOR2_X1 g256(.A (cnt[26]), .B (cnt[23]), .Z (n_42));
  XNOR2_X1 g257(.A (cnt[24]), .B (cnt[26]), .ZN (n_41));
  XNOR2_X1 g258(.A (cnt[25]), .B (cnt[26]), .ZN (n_40));
  NOR2_X1 g259(.A1 (cnt[22]), .A2 (cnt[26]), .ZN (n_39));
  DFF_X1 \pwm_cnt_reg[3] (.CK (clk), .D (n_36), .Q (pwm_cnt[3]), .QN
       (n_38));
  NOR2_X1 g86(.A1 (reset), .A2 (n_35), .ZN (n_36));
  DFF_X1 \pwm_cnt_reg[2] (.CK (clk), .D (n_34), .Q (pwm_cnt[2]), .QN
       (UNCONNECTED0));
  XOR2_X1 g88(.A (n_31), .B (pwm_cnt[3]), .Z (n_35));
  NOR2_X1 g89(.A1 (reset), .A2 (n_32), .ZN (n_34));
  DFF_X1 \pwm_cnt_reg[1] (.CK (clk), .D (n_33), .Q (pwm_cnt[1]), .QN
       (n_0));
  NOR2_X1 g91(.A1 (reset), .A2 (n_30), .ZN (n_33));
  XNOR2_X1 g92(.A (n_29), .B (pwm_cnt[2]), .ZN (n_32));
  DFF_X1 \cnt_reg[11] (.CK (clk), .D (n_26), .Q (cnt[11]), .QN
       (UNCONNECTED1));
  DFF_X1 \cnt_reg[12] (.CK (clk), .D (n_28), .Q (cnt[12]), .QN
       (UNCONNECTED2));
  DFF_X1 \cnt_reg[13] (.CK (clk), .D (n_27), .Q (cnt[13]), .QN
       (UNCONNECTED3));
  DFF_X1 \cnt_reg[14] (.CK (clk), .D (n_25), .Q (cnt[14]), .QN
       (UNCONNECTED4));
  DFF_X1 \cnt_reg[15] (.CK (clk), .D (n_24), .Q (cnt[15]), .QN
       (UNCONNECTED5));
  DFF_X1 \cnt_reg[16] (.CK (clk), .D (n_23), .Q (cnt[16]), .QN
       (UNCONNECTED6));
  DFF_X1 \cnt_reg[17] (.CK (clk), .D (n_22), .Q (cnt[17]), .QN
       (UNCONNECTED7));
  DFF_X1 \cnt_reg[18] (.CK (clk), .D (n_21), .Q (cnt[18]), .QN
       (UNCONNECTED8));
  DFF_X1 \cnt_reg[19] (.CK (clk), .D (n_20), .Q (cnt[19]), .QN
       (UNCONNECTED9));
  DFF_X1 \cnt_reg[1] (.CK (clk), .D (n_19), .Q (cnt[1]), .QN
       (UNCONNECTED10));
  DFF_X1 \cnt_reg[20] (.CK (clk), .D (n_18), .Q (cnt[20]), .QN
       (UNCONNECTED11));
  DFF_X1 \cnt_reg[21] (.CK (clk), .D (n_17), .Q (cnt[21]), .QN
       (UNCONNECTED12));
  DFF_X1 \cnt_reg[22] (.CK (clk), .D (n_16), .Q (cnt[22]), .QN
       (UNCONNECTED13));
  DFF_X1 \cnt_reg[23] (.CK (clk), .D (n_15), .Q (cnt[23]), .QN
       (UNCONNECTED14));
  DFF_X1 \cnt_reg[24] (.CK (clk), .D (n_13), .Q (cnt[24]), .QN
       (UNCONNECTED15));
  DFF_X1 \cnt_reg[26] (.CK (clk), .D (n_10), .Q (cnt[26]), .QN
       (UNCONNECTED16));
  DFF_X1 \cnt_reg[2] (.CK (clk), .D (n_9), .Q (cnt[2]), .QN
       (UNCONNECTED17));
  DFF_X1 \cnt_reg[3] (.CK (clk), .D (n_8), .Q (cnt[3]), .QN
       (UNCONNECTED18));
  DFF_X1 \cnt_reg[4] (.CK (clk), .D (n_6), .Q (cnt[4]), .QN
       (UNCONNECTED19));
  DFF_X1 \cnt_reg[5] (.CK (clk), .D (n_5), .Q (cnt[5]), .QN
       (UNCONNECTED20));
  DFF_X1 \cnt_reg[6] (.CK (clk), .D (n_11), .Q (cnt[6]), .QN
       (UNCONNECTED21));
  DFF_X1 \cnt_reg[7] (.CK (clk), .D (n_4), .Q (cnt[7]), .QN
       (UNCONNECTED22));
  DFF_X1 \cnt_reg[25] (.CK (clk), .D (n_12), .Q (cnt[25]), .QN
       (UNCONNECTED23));
  DFF_X1 \cnt_reg[9] (.CK (clk), .D (n_3), .Q (cnt[9]), .QN
       (UNCONNECTED24));
  DFF_X1 \cnt_reg[8] (.CK (clk), .D (n_14), .Q (cnt[8]), .QN
       (UNCONNECTED25));
  DFF_X1 \cnt_reg[10] (.CK (clk), .D (n_7), .Q (cnt[10]), .QN
       (UNCONNECTED26));
  DFF_X1 \cnt_reg[0] (.CK (clk), .D (n_2), .Q (cnt[0]), .QN (n_79));
  NAND2_X1 g120(.A1 (n_29), .A2 (pwm_cnt[2]), .ZN (n_31));
  XNOR2_X1 g121(.A (pwm_cnt[1]), .B (cnt[0]), .ZN (n_30));
  NOR2_X1 g122(.A1 (n_79), .A2 (n_0), .ZN (n_29));
  AND2_X1 g123(.A1 (n_65), .A2 (n_1), .ZN (n_28));
  AND2_X1 g124(.A1 (n_64), .A2 (n_1), .ZN (n_27));
  AND2_X1 g125(.A1 (n_66), .A2 (n_1), .ZN (n_26));
  AND2_X1 g126(.A1 (n_63), .A2 (n_1), .ZN (n_25));
  AND2_X1 g127(.A1 (n_62), .A2 (n_1), .ZN (n_24));
  AND2_X1 g128(.A1 (n_61), .A2 (n_1), .ZN (n_23));
  AND2_X1 g129(.A1 (n_60), .A2 (n_1), .ZN (n_22));
  AND2_X1 g130(.A1 (n_59), .A2 (n_1), .ZN (n_21));
  AND2_X1 g131(.A1 (n_58), .A2 (n_1), .ZN (n_20));
  AND2_X1 g132(.A1 (n_76), .A2 (n_1), .ZN (n_19));
  AND2_X1 g133(.A1 (n_57), .A2 (n_1), .ZN (n_18));
  AND2_X1 g134(.A1 (n_56), .A2 (n_1), .ZN (n_17));
  AND2_X1 g135(.A1 (n_55), .A2 (n_1), .ZN (n_16));
  AND2_X1 g136(.A1 (n_54), .A2 (n_1), .ZN (n_15));
  AND2_X1 g137(.A1 (n_69), .A2 (n_1), .ZN (n_14));
  AND2_X1 g138(.A1 (n_53), .A2 (n_1), .ZN (n_13));
  AND2_X1 g139(.A1 (n_52), .A2 (n_1), .ZN (n_12));
  AND2_X1 g140(.A1 (n_71), .A2 (n_1), .ZN (n_11));
  AND2_X1 g141(.A1 (n_51), .A2 (n_1), .ZN (n_10));
  AND2_X1 g142(.A1 (n_75), .A2 (n_1), .ZN (n_9));
  AND2_X1 g143(.A1 (n_74), .A2 (n_1), .ZN (n_8));
  AND2_X1 g144(.A1 (n_67), .A2 (n_1), .ZN (n_7));
  AND2_X1 g145(.A1 (n_73), .A2 (n_1), .ZN (n_6));
  AND2_X1 g146(.A1 (n_72), .A2 (n_1), .ZN (n_5));
  AND2_X1 g147(.A1 (n_70), .A2 (n_1), .ZN (n_4));
  AND2_X1 g148(.A1 (n_68), .A2 (n_1), .ZN (n_3));
  NOR2_X1 g149(.A1 (reset), .A2 (cnt[0]), .ZN (n_2));
  INV_X1 g152(.A (reset), .ZN (n_1));
endmodule

